# inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/models/concerns/sortable.rb'
    - 'lib/will_paginate_boostrap4_renderer.rb'
    - 'lib/hm_form_builder.rb'


Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20