production:
  adapter: postgresql
  encoding: unicode
  database: mobility_toolbox_production
  pool: 5
  username: <%= ENV['FABRIQUE_MOBILITE_DB_USER'] %>
  password: <%= ENV['FABRIQUE_MOBILITE_DB_PASSWORD'] %>
  host: localhost